### ISSUE TITLE
review of marketing tools -> create second landing (1)

### ISSUE THREAD

**Issue by tomaszzygadlo** [gustawdaniel/da_automation#4]
sales manago?

**Comment by gustawdaniel** [comment]
Issue should be closed when marketing tools will be reviewed and best will be chosen and applied.

**Comment by gustawdaniel** [comment]
Tools List

- [x] Mail Chimp #8
- [x] HubSpot -> 

Do course: https://offers.hubspot.com/marketing-in-2020?hubs_post-cta=blog-homepage&hsCtaTracking=3630a366-5e32-4671-9584-26004317350c%7C078e6880-bb25-4777-b5c2-ae721dafa406

- [x] Sales manage seems to be rather expensive. I propose wait with this to moment, when we will get income. 

- [x] Google Analytics -> asked on telegram

**Comment by gustawdaniel** [comment]
@tomaszzygadlo please write your opinion about sales manago vs hubspot. I checked both and think that hub spot is better choice because prices and my user experience.

External opinions:

1) Hubspot wins in price and `Total Score `

> https://comparisons.financesonline.com/hubspot-vs-salesmanago

2) Hubspot sales module vs Sale manago, again hubspot wins

> https://comparisons.financesonline.com/salesmanago-vs-hubspot-sales

3) Hubspot slightly wins in score, but much more popular

> https://www.g2crowd.com/compare/hubspot-vs-salesmanago

4) Rather equal results but really comprehensive, exhaustive comparison

> https://www.getapp.com/marketing-software/a/hubspot-inbound-marketing-software/compare/salesmanago-marketing-automation/

**Comment by gustawdaniel** [comment]
To close this issue we need:

1) Second landing
2) Emails collecting with hubspot
3) Deals creation on hubspot 
4) Emails sending to MailChimp -> #8 - think about email campaign (when emails will be collected at least 100) MailChimp is free up to 2000 subscribers and 12k emails by month, next $10 so not problem.

> https://mailchimp.com/pricing/

5) Decision about using sales manago / hubspot will be made.
6) Documentation with index of all used by us external services will be created.
7) Table with checklist about acces to any service will be created.
